### ISSUE TITLE
Calling for cutomer list cause an error of JSON parsing in email field

### ISSUE THREAD

**Issue by sphinks** [helpscout/helpscout-api-java#28]
Couple days ago I have been running my integration test and they passed. Today I have faced with exception during parsing of Customer data: 

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
    at com.google.gson.Gson.fromJson(Gson.java:795)
    at com.google.gson.Gson.fromJson(Gson.java:859)
    at com.google.gson.Gson.fromJson(Gson.java:832)
    at net.helpscout.api.Parser.getObject(Parser.java:63)
    at net.helpscout.api.utils.JSONUtils.getPageItems(JSONUtils.java:52)
    at net.helpscout.api.utils.JSONUtils.objectToPage(JSONUtils.java:42)
    at net.helpscout.api.ApiClient.getPage(ApiClient.java:1451)
    at net.helpscout.api.ApiClient.getPage(ApiClient.java:1434)
    at net.helpscout.api.ApiClient.getCustomers(ApiClient.java:642)
    at net.helpscout.api.ApiClient.getCustomers(ApiClient.java:628)
    at net.helpscout.api.ApiIntegrationTests.conversationCreateReadDeleteTest(ApiIntegrationTests.java:135)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)

```

I have traced a little bit. Problem is located in response from server:

```
{"id":76688730,
"firstName":"name",
"lastName":"last_name",
"fullName":"name last_name",
"emails":["email@somewhere.com"],
"photoUrl":null,
"photoType":null,
"gender":"unknown",
"age":null,
"organization":null,
"jobTitle":null,
"location":null,
"createdAt":"2016-03-21T21:18:58Z",
"modifiedAt":"2016-03-21T21:19:17Z"}
```

Parsing goes well until coming to emails. In Java object `Customer` here expected array of objects `EmailEntry`, meanwhile recieved array of Strings. So GSON lib fails at:

```
public void beginObject() throws IOException {
        this.expect(JsonToken.BEGIN_OBJECT);
    }
```

As far as I understand, begin_object in this case should be symbol `{`, but String start symbol is met, so it cause an exception. 

Are there any changes in the logic of JSON response creating on the server side? Accroding to API docs http://developer.helpscout.net/help-desk-api/objects/email/ it is incorrect format. I suppose, server side should be fixed or wrapper should be corrected according to format.

**Comment by sphinks** [comment]
In unit test I have found data sample of customer data and emails there placed in such way:

```
...
"emails": [
            {
                "id": 76610693,
                "value": "petersmith@fakeemail.com",
                "location": "work"
            },
            {
                "id": 77590346,
                "value": "petersmithwork@fakeemail.com",
                "location": "work"
            }
        ],
...
```

Format of response are changed for sure.

**Comment by sphinks** [comment]
I have rerun tests once again today and seem like everything is working as expected. Return format is the same as before. Issue could be closed.
